# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [2]:
%pip install pandas numpy  matplotlib  seaborn  scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd

In [4]:
pd

<module 'pandas' from '/home/abyssde232024/mlzoomcamp2024/machine-learning-zoomcamp/.venv/lib/python3.10/site-packages/pandas/__init__.py'>

In [5]:
pd.__version__

'2.2.3'

In [6]:
import numpy as np

In [7]:
np

<module 'numpy' from '/home/abyssde232024/mlzoomcamp2024/machine-learning-zoomcamp/.venv/lib/python3.10/site-packages/numpy/__init__.py'>

## Creating arrays


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  5,  7, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2, 11, 2) 

array([ 2,  4,  6,  8, 10])

In [21]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Multi-dimensional arrays


In [22]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [32]:
b= [[11, 12, 13], ["a", "b", "c"], [17, 18, 19]]
b= [[11, 12, 13], [14, 15, 16], [17, 18, 19]]

In [33]:
m = np.array(b)
m
m*2

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [36]:
m[0, 1] = 20

In [37]:
m

array([[11, 20, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [38]:
m[2] = [1, 1, 1]

In [39]:
m

array([[11, 20, 13],
       [14, 15, 16],
       [ 1,  1,  1]])

In [40]:
n[:, 2] = [0, 1, 2]

In [41]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

## Randomly generated arrays


In [43]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [48]:
np.random.seed(3)
np.random.rand(5,3, 2)

array([[[0.5507979 , 0.70814782],
        [0.29090474, 0.51082761],
        [0.89294695, 0.89629309]],

       [[0.12558531, 0.20724288],
        [0.0514672 , 0.44080984],
        [0.02987621, 0.45683322]],

       [[0.64914405, 0.27848728],
        [0.6762549 , 0.59086282],
        [0.02398188, 0.55885409]],

       [[0.25925245, 0.4151012 ],
        [0.28352508, 0.69313792],
        [0.44045372, 0.15686774]],

       [[0.54464902, 0.78031476],
        [0.30636353, 0.22195788],
        [0.38797126, 0.93638365]]])

In [49]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [50]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [57]:
a = np.arange(5)
a = np.random.randint(0, 100, size=(5, 2))
a

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

In [58]:
b = (10 + (a * 2)) ** 2 / 100

In [59]:
b

array([[213.16, 104.04],
       [225.  , 400.  ],
       [309.76,  51.84],
       [201.64, 289.  ],
       [129.96, 262.44]])

In [60]:
a / b + 10

array([[10.31900919, 10.44213764],
       [10.31111111, 10.2375    ],
       [10.26794938, 10.59799383],
       [10.32731601, 10.27681661],
       [10.40012311, 10.28959   ]])

## Comparison operations

In [61]:
a

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

In [66]:
a[4][1]

np.int64(76)

In [67]:
a >= 60

array([[ True, False],
       [ True,  True],
       [ True, False],
       [ True,  True],
       [False,  True]])

In [68]:
b

array([[213.16, 104.04],
       [225.  , 400.  ],
       [309.76,  51.84],
       [201.64, 289.  ],
       [129.96, 262.44]])

In [69]:
a > b

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [71]:
a[a > b/45]

array([68, 46, 70, 95, 83, 31, 66, 80, 52, 76])

## Summarizing operations

In [72]:
a

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

In [73]:
a.std()

np.float64(18.06128456118224)

In [75]:
m.min()

np.int64(1)

In [78]:
m.max()

np.int64(20)

### Next

Linear algebra refresher