# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [2]:
import numpy as np

In [11]:
### Vector operations
u = np.array([2, 7, 5, 9])
v = np.array([3, 4, 8, 6])

# addition 
u + v



array([ 5, 11, 13, 15])

In [12]:
# subtraction 
u - v


array([-1,  3, -3,  3])

In [13]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

## Vector operations

In [14]:
u = np.array([2, 4, 5, 6])

In [15]:
2 * u

array([ 4,  8, 10, 12])

In [26]:
v = np.array([1, 0, 3, 2])

In [27]:
u + v

array([3, 4, 8, 8])

In [28]:
u * v

array([ 2,  0, 15, 12])

## Multiplication

In [29]:
v.shape

(4,)

In [30]:
v.shape[0]

4

In [31]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [32]:
vector_vector_multiplication(u, v)

np.float64(29.0)

In [33]:
u.dot(v)

np.int64(29)

In [34]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [35]:
U.shape

(3, 4)

In [36]:
v

array([1, 0, 3, 2])

In [37]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    print(result)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [38]:
matrix_vector_multiplication(U, v)

[0. 0. 0.]


array([29.,  8., 11.])

In [39]:
U.dot(v)

array([29,  8, 11])

In [40]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [42]:
U.shape

(3, 4)

In [41]:

V.shape

(4, 3)

In [52]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        # print(f"vi value is {vi}")
        Uvi = matrix_vector_multiplication(U, vi)
        print(f"Uvi value is {Uvi}")
        result[:, i] = Uvi
        print(f"result value is {result}")
    
    return result

In [53]:
matrix_matrix_multiplication(U, V)

[0. 0. 0.]
Uvi vale is [14.  5.  5.]
result vale is [[14.  0.  0.]
 [ 5.  0.  0.]
 [ 5.  0.  0.]]
[0. 0. 0.]
Uvi vale is [20.   6.   8.5]
result vale is [[14.  20.   0. ]
 [ 5.   6.   0. ]
 [ 5.   8.5  0. ]]
[0. 0. 0.]
Uvi vale is [13.  5.  9.]
result vale is [[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [51]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [54]:
I = np.eye(3)

In [55]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [57]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [58]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [59]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [60]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas